font_family PxPlus IBM VGA 8
bold_font auto
italic_font auto
bold_italic_font auto
enable_audio_bell no
window_padding_width 5 5 5 5
font_size 18
cursor_shape beam
cursor_blink_interval 0.5
background #000000
allow_remote_control yes
modify_font cell_height 120%
