#!/bin/sh
battery() {
    BAT="$(ls -d /sys/class/power_supply/BAT* 2>/dev/null | head -n 1)"
    CAP="$(cat "$BAT/capacity")"
    STATUS="$(cat "$BAT/status")"

    case "$STATUS" in
        Charging)    ICON=" (Charging)" ;;
        Discharging) ICON=" (Discharging)" ;;
        *) ICON="" ;;
    esac

    printf "%s%%%s" "$CAP" "$ICON"
}
internet() {
    IFACE="$(ip route show default 2>/dev/null | awk 'NR==1 {
            print $5
    }')"
    STATE="$(cat /sys/class/net/$IFACE/operstate 2>/dev/null)"

    if [ "$STATE" = "up" ]; then
        printf "Connected to internet"
    else
        printf "No internet connection"
    fi
}
#vol() {
#    if pamixer --get-mute | grep -q true; then
#        printf "Mute"
#    else
#        printf "%s%%" "$(pamixer --get-volume)"
#    fi
#}
while true; do
    xsetroot -name "ALT+SHIFT+ENTER to open menu   Battery: $(battery)   $(internet)   Date: $(date '+%d/%m/%Y %H:%M')"
    sleep 5
done
