#!/bin/sh
battery() {
    BAT="$(ls -d /sys/class/power_supply/BAT* 2>/dev/null | head -n 1)"
    CAP="$(cat "$BAT/capacity")"
    printf "%s%%" "$CAP"
}
internet() {
    IFACE="$(ip route show default 2>/dev/null | awk 'NR==1 {
            print $5
    }')"
    STATE="$(cat /sys/class/net/$IFACE/operstate 2>/dev/null)"

    if [ "$STATE" = "up" ]; then
        printf "UP"
    else
        printf "DWN"
    fi
}
while true; do
    xsetroot -name "$(battery)   $(internet)   $(date '+%H:%M')"
    sleep 5
done
